# Generated by Django 5.0.6 on 2024-06-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='product_qty',
        ),
    ]
